Add configureBaker support
Concordium/concordium-node-sdk-js pull request #133
Opened 2023-02-09 09:27 UTC by shjortConcordium

## Purpose

Support `configureBaker` transactions

## Changes

Added serialization for `configureBaker`.
Added a function to generate baker keys.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2023-02-15 12:03 UTC, rasmus-kirk requested changes

2023-02-15 12:03 UTC, rasmus-kirk commented on packages/common/src/serializationHelpers.ts
> +const serializeUrl = (url: string) => {
Same question as the related comment, should we have an `UrlString`?

2023-02-15 14:21 UTC, shjortConcordium commented on packages/common/src/types.ts
> +}
They are settings, so only if you want to configure a setting, do you include it.

2023-02-15 14:21 UTC, shjortConcordium commented on packages/common/src/serializationHelpers.ts
> +}
I think it is a serializationHelper, but I'll export/document.

2023-02-15 14:59 UTC, shjortConcordium commented on packages/rust-bindings/src/external_functions.rs
> +pub fn generate_baker_keys_ext(sender: &str) -> String {
Sure, I've done it for a couple other functions also.

2023-02-16 09:36 UTC, rasmus-kirk approved these changes

2023-02-16 11:48 UTC, merged