Add section on constructing identity input in README
Concordium/concordium-node-sdk-js pull request #25
Opened 2021-12-15 07:46 UTC by shjortConcordium

## Purpose

Add section to README to help constructing identityInputs for creating credentials/accounts.

2021-12-15 07:50 UTC, abizjak commented on README.md
> +Below is an example of how to construct the identityInput, with a plantext id-use-data.json from the [user-cli guide](https://github.com/Concordium/concordium-base/blob/main/rust-bins/docs/user-cli.m
Perhaps add a subsection heading here to delineate this example from the one below.

2021-12-15 07:50 UTC, abizjak commented on README.md
> +Next is an example of how to construct the identityInput for the  _i_-th identity from a mobile wallet export:
And a subsection heading here as well.

2021-12-15 10:20 UTC, abizjak approved these changes

2021-12-16 09:39 UTC, orhoj commented on README.md
> +## Construct identityInput for creating credentials
```suggestion
## Construct IdentityInput for creating credentials
```

2021-12-16 09:43 UTC, orhoj commented on README.md
> +When creating a new identity, the user will choose an identity provider, create an id-use-data object, which contains the private data to use the identity, and obtain an identity object from the iden
```suggestion
When creating a new identity the user will choose an identity provider, create an id-use-data object, which contains the private data to use for the identity, and obtain an identity object from the identity provider.
```

2021-12-16 09:49 UTC, orhoj commented on README.md
> +    'path/to/id-use-data',
```suggestion
    'path/to/id-use-data.json',
```

2021-12-16 09:49 UTC, orhoj commented on README.md
> +    'path/to/id-object',
```suggestion
    'path/to/id-object.json',
```

2021-12-16 09:50 UTC, orhoj requested changes
The mobile wallet export default file extension could also be added.

2021-12-16 10:49 UTC, orhoj approved these changes

2021-12-16 10:49 UTC, merged